rockmat = manager:loadmaterial("materials/standard planet pack/rock/"..manager:getsetting("graphicstype")..".mat")
cube = mapfunctions:createcube()
plane = mapfunctions:createplane()
mapfunctions:spawnobjects(0, 0, 0, 50, 50, 0, 0, 0, 0, plane, 0, mapname, rockmat)
obj = mapfunctions:spawnobject(0, 0, 20, 0, 0, 0, cube, 1, mapname)
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightcolor(obj, 0.25, 0.43, 0.15, 1)
mapfunctions:setlightintensity(obj, 1.5)
mapfunctions:setlightrange(obj, 50)
mapfunctions:destroyobj(cube)
mapfunctions:destroyobj(plane)
manager:addfunction("maps/curg/lightning.lua", "update", mapname)
