rockmat = manager:loadmaterial("materials/standard planet pack/rock/"..manager:getsetting("graphicstype")..".mat")
rockmat2 = manager:loadmaterial("materials/standard planet pack/rock/"..manager:getsetting("graphicstype")..".mat")
metalmat = manager:loadmaterial("materials/standard metal pack/metal6/"..manager:getsetting("graphicstype")..".mat")
plane = mapfunctions:createplane()
cube = mapfunctions:createcube()
obj = mapfunctions:spawnobject(0, 0, 20, 0, 0, 0, cube, 1, mapname)
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightcolor(obj, 0.533, 0.301, 0.255, 1)
mapfunctions:setlightintensity(obj, 50)
mapfunctions:setlightrange(obj, 55)
mapfunctions:spawnobjects(-50, 0, 0, 50, 50, 0, 0, 0, 0, plane, 0, mapname, rockmat)
mapfunctions:spawnobjects(-50, 50, 0, -1, 50, 10, 0, 0, 0, cube, 1, mapname, rockmat2)
mapfunctions:spawnobjects(1, 50, 0, 50, 50, 10, 0, 0, 0, cube, 1, mapname, rockmat2)
mapfunctions:spawnobjects(0, 50, 1, 0, 50, 10, 0, 0, 0, cube, 1, mapname, rockmat2)
mapfunctions:spawnlocation(0, 50, 0, 0, 50, 3, mapname, mapname)
mapfunctions:destroyobj(cube)
mapfunctions:destroyobj(plane)
