mat1 = manager:loadmaterial("materials/standard metal pack/metal2/"..manager:getsetting("graphicstype")..".mat")
mat2 = manager:loadmaterial("materials/standard metal pack/metal4/"..manager:getsetting("graphicstype")..".mat")
manager:setproperty(mat1, "_ShadowIntensity", 1)
manager:setproperty(mat2, "_ShadowIntensity", 1)
manager:setproperty(mat1, "_E3Power", 5)
plane = mapfunctions:createplane()
cube = mapfunctions:createcube()
mapfunctions:spawnobjects(-1, -1, 0, 30, -1, 3, 0, 0, 0, cube, 1, mapname, mat1)
mapfunctions:spawnlocation(10, 0, 0, 10, 0, 3, mapname, mapname)
mapfunctions:spawnobjects(0, 0, 0, 30, 30, 0, 0, 0, 0, plane, 0, mapname, mat2)
mapfunctions:spawnobjects(0, 0, 3, 30, 30, 3, 180, 0, 0, plane, 1, mapname, mat1)
mapfunctions:spawnobjects(-1, -1, 0, -1, 30, 3, 0, 270, 0, cube, 1, mapname, mat1)
mapfunctions:spawnobjects(30, -1, 0, 30, 30, 3, 0, 90, 0, cube, 1, mapname, mat1)
mapfunctions:spawnobjects(-1, 30, 0, 30, 30, 3, 0, 0, 0, cube, 1, mapname, mat1)
obj = mapfunctions:getobj(10, 20, 3, "plane", manager:findmap(mapname))
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightcolor(obj, 0.7, 0.5, 0.3, 1)
mapfunctions:setlightrange(obj, 35)
mapfunctions:setlightintensity(obj, 10)
mapfunctions:spawnlocation(20, 29, 0, 20, 29, 3, mapname, mapname)
mapfunctions:destroyobj(plane)
mapfunctions:destroyobj(cube)
