mat1 = manager:loadmaterial("materials/standard metal pack/steel/"..manager:getsetting("graphicstype")..".mat")
mat2 = manager:loadmaterial("materials/standard metal pack/metal3/"..manager:getsetting("graphicstype")..".mat")
plane = mapfunctions:createplane()
cube = mapfunctions:createcube()
mapfunctions:spawnobjects(0, 0, 0, 20, 9, 0, 0, 0, 0, plane, 0, mapname, mat2)
mapfunctions:spawnobjects(0, 0, 6, 20, 9, 6, 180, 0, 0, plane, 1, mapname, mat1)
mapfunctions:spawnobjects(-1, 0, 0, -1, 9, 6, 0, 270, 0, cube, 1, mapname, mat1)
mapfunctions:spawnobjects(20, 0, 0, 20, 9, 6, 0, 90, 0, cube, 1, mapname, mat1)
obj = mapfunctions:getobj(10, 5, 6, "plane", manager:findmap(mapname))
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightrange(obj, 15)
mapfunctions:setlightcolor(obj, 0.7, 0.5, 0.1, 1)
mapfunctions:setlightintensity(obj, 10)
mapfunctions:spawnlocation(10, 9, 0, 10, 9, 6, mapname, mapname)
obj = mapfunctions:getobj(-1, 1, 1, "cube", manager:findmap(mapname))
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightrange(obj, 2)
mapfunctions:setlightintensity(obj, 10)
mapfunctions:setlightcolor(obj, 0.45, 0.1, 0.3, 1)
mapfunctions:destroyobj(cube)
mapfunctions:destroyobj(plane)
mapfunctions:spawnlocation(0, 0, 0, 0, 0, 3, mapname, mapname)
