metalmat = manager:loadmaterial("materials/standard metal pack/metal6/"..manager:getsetting("graphicstype")..".mat")
rockmat = manager:loadmaterial("materials/standard planet pack/rock/"..manager:getsetting("graphicstype").."-2.mat")
manager:setproperty(rockmat, "_MistDensity", 0.0)
manager:setproperty(metalmat, "_MistDensity", 0.0)
manager:setproperty(rockmat, "_FogIntensity", 0.1)
manager:setproperty(metalmat, "_FogIntensity", 0.1)
plane = mapfunctions:createplane()
cube = mapfunctions:createcube()
mapfunctions:spawnobjects(0, 0, 0, 10, 20, 0, 0, 0, 0, plane, 0, mapname, rockmat)
mapfunctions:spawnobjects(0, 0, 3, 10, 20, 3, 180, 0, 0, plane, 1, mapname, metalmat)
mapfunctions:spawnobjects(-1, 0, 0, -1, 20, 3, 0, 270, 0, cube, 1, mapname, rockmat)
mapfunctions:spawnobjects(-1, 20, 0, 10, 20, 3, 0, 0, 0, cube, 1, mapname, rockmat)
mapfunctions:spawnobjects(10, 0, 0, 10, 15, 3, 0, 90, 0, cube, 1, mapname, rockmat)
mapfunctions:spawnlocation(0, 0, 0, 10, 0, 3, mapname, mapname)
mapfunctions:destroyobj(plane)
mapfunctions:destroyobj(cube)
obj = mapfunctions:getobj(5, 5, 3, "plane", manager:findmap(mapname))
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightrange(obj, 20)
mapfunctions:setlightintensity(obj, 2)
mapfunctions:setlightcolor(obj, 0.7, 0.25, 0.3, 1)
mapfunctions:spawnlocation(10, 15, 0, 10, 20, 3, mapname, mapname)
