rockmat = manager:loadmaterial("materials/standard planet pack/rock/"..manager:getsetting("graphicstype")..".mat")
rockmat2 = manager:loadmaterial("materials/standard planet pack/rock/"..manager:getsetting("graphicstype").."-2.mat")
watermat = manager:loadmaterial("materials/standard planet pack/water/"..manager:getsetting("graphicstype")..".mat")
plane = mapfunctions:createplane()
cube = mapfunctions:createcube()
mapfunctions:spawnobjects(0, 0, -2, 10, 20, -2, 0, 0, 0, plane, 1, mapname, rockmat)
mapfunctions:spawnobjects(0, 0, -1, 10, 20, 0, 0, 0, 0, plane, 0, mapname, watermat)
mapfunctions:spawnobjects(-1, -1, 0, -1, 20, 9, 0, 270, 0, cube, 1, mapname, rockmat2)
mapfunctions:spawnobjects(10, -1, 0, 10, 20, 9, 0, 90, 0, cube, 1, mapname, rockmat2)
mapfunctions:destroyobj(cube)
mapfunctions:destroyobj(plane)
mapfunctions:spawnlocation(0, 0, 0, 19, 50, 0, mapname, mapname)
obj = mapfunctions:getobj(0, 10, 0, "plane", manager:findmap(mapname))
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightrange(obj, 20)
mapfunctions:setlightcolor(obj, 0.8, 0.7, 0.2, 1)
mapfunctions:setlightintensity(obj, 5)
obj = mapfunctions:getobj(9, 10, 0, "plane", manager:findmap(mapname))
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightrange(obj, 20)
mapfunctions:setlightcolor(obj, 0.8, 0.7, 0.2, 1)
mapfunctions:setlightintensity(obj, 5)
