metalmat = manager:loadmaterial("materials/standard metal pack/metal6/"..manager:getsetting("graphicstype")..".mat")
rockmat = manager:loadmaterial("materials/standard planet pack/rock/"..manager:getsetting("graphicstype").."-2.mat")
rockmat2 = manager:loadmaterial("materials/standard planet pack/rock2/"..manager:getsetting("graphicstype")..".mat")
cliffmat = manager:loadmaterial("materials/standard planet pack/cliff/"..manager:getsetting("graphicstype")..".mat")
manager:setproperty(rockmat, "_FogIntensity", 0.1)
manager:setproperty(rockmat, "_MistDensity", 0.1)
manager:setproperty(rockmat2, "_FogIntensity", 0.1)
manager:setproperty(rockmat2, "_MistDensity", 0.1)
manager:setproperty(metalmat, "_FogIntensity", 0.1)
manager:setproperty(metalmat, "_MistDensity", 0.1)
cube = mapfunctions:createcube()
plane = mapfunctions:createplane()
mapfunctions:spawnobjects(0, 0, 0, 10, 10, 3, 0, 0, 0, plane, 0, mapname, rockmat)
mapfunctions:spawnobjects(0, 0, 3, 10, 20, 3, 180, 0, 0, plane, 1, mapname, metalmat)
mapfunctions:spawnobjects(-1, -1, 0, 10, -1, 3, 0, 180, 0, cube, 1, mapname, rockmat)
mapfunctions:spawnobjects(-1, 5, 0, -1, 20, 3, 0, 270, 0, cube, 1, mapname, rockmat)
mapfunctions:spawnobjects(10, -1, 0, 10, 20, 3, 0, 90, 0, cube, 1, mapname, rockmat)
mapfunctions:spawnobjects(-1, 10, -8, 10, 10, -1, 0, 0, 0, cube, 1, mapname, rockmat2)
mapfunctions:spawnobjects(-1, 10, -9, 10, 10, -9, 0, 0, 0, cube, 1, mapname, cliffmat)
mapfunctions:destroyobj(cube)
mapfunctions:destroyobj(plane)
obj = mapfunctions:getobj(5, 5, 3, "plane", manager:findmap(mapname))
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightcolor(obj, 0.7, 0.3, 0.1, 1)
mapfunctions:setlightintensity(obj, 7)
mapfunctions:setlightrange(obj, 10)
mapfunctions:spawnlocation(0, 0, 0, 0, 4, 3, mapname, mapname)
mapfunctions:spawnrunscript(-1, 11, 0, 10, 20, 3, "maps/Bodie V/geoplant/drop1.lua", mapname)
obj = mapfunctions:getobj(5, 10, -9, "cube", manager:findmap(mapname))
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightrange(obj, 5)
mapfunctions:setlightcolor(obj, 0.3, 0.1, 0.7, 1)
mapfunctions:setlightintensity(obj, 5)
manager:addfunction("maps/Bodie V/geoplant/ledge.lua", "update", mapname)
