foundmap = manager:findmap(mapname)
maxx = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "maxx"))
maxy = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "maxy"))
maxz = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "maxz"))
floor = manager:loadmaterial(mapfunctions:checkstatetext(foundmap, "floor").."/"..manager:getsetting("graphicstype")..".mat")
ceeling = manager:loadmaterial(mapfunctions:checkstatetext(foundmap, "ceeling").."/"..manager:getsetting("graphicstype")..".mat")
wall = manager:loadmaterial(mapfunctions:checkstatetext(foundmap, "wall").."/"..manager:getsetting("graphicstype")..".mat")
plane = mapfunctions:createplane()
cube = mapfunctions:createcube()
mapfunctions:spawnobjects(0, 0, 0, maxx, maxy, 0, 0, 0, 0, plane, 0, mapname, floor)
mapfunctions:spawnobjects(0, 0, maxz, maxx, maxy, maxz, 180, 0, 0, plane, 1, mapname, ceeling)
mapfunctions:spawnobjects(-1, -1, 0, -1, maxy, maxz, 0, 270, 0, cube, 1, mapname, wall)
mapfunctions:spawnobjects(maxx, 0, 0, maxx, maxy, maxz, 0, 90, 0, cube, 1, mapname, wall)
mapfunctions:spawnobjects(-1, maxy, 0, maxx, maxy, maxz, 0, 0, 0, cube, 1, mapname, wall)
mapfunctions:spawnobjects(-1, -1, 0, maxx, -1, maxz, 0, 180, 0, cube, 1, mapname, wall)
mapfunctions:destroyobj(plane)
mapfunctions:destroyobj(cube)
