plane = mapfunctions:createplane()
cube = mapfunctions:createcube()
metalmat = manager:loadmaterial("materials/standard metal pack/metal/"..manager:getsetting("graphicstype")..".mat")
metal2mat = manager:loadmaterial("materials/standard metal pack/metal2/"..manager:getsetting("graphicstype")..".mat")
foundmap = manager:findmap(mapname)
mapfunctions:spawnobjects(0, 0, 0, 10, 10, 0, 0, 0, 0, plane, 0, mapname, metalmat)
mapfunctions:spawnobjects(0, 0, 5, 10, 10, 5, 180, 0, 0, plane, 1, mapname, metalmat)
mapfunctions:spawnobjects(-1, -1, 0, -1, 10, 5, 0, 270, 0, cube, 1, mapname, metal2mat)
mapfunctions:spawnobjects(10, -1, 0, 10, 10, 5, 0, 90, 0, cube, 1, mapname, metal2mat)
mapfunctions:spawnobjects(-1, 10, 0, 10, 10, 5, 0, 0, 0, cube, 1, mapname, metal2mat)
mapfunctions:spawnobjects(-1, -1, 0, 10, -1, 5, 0, 180, 0, cube, 1, mapname, metal2mat)
obj = mapfunctions:getobj(5, 5, 5, "plane", manager:findmap(mapname))
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightrange(obj, 7)
mapfunctions:setlightintensity(obj, 20)
mapfunctions:setlightcolor(obj, 0.5, 0.5, 0.5, 1)
obj = mapfunctions:getobj(0, 2, 5, "plane", manager:findmap(mapname))
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightcolor(obj, 0.5, 0.5, 0.5, 1)
mapfunctions:setlightrange(obj, 6)
mapfunctions:setlightintensity(obj, 20)
obj = mapfunctions:getobj(0, 8, 5, "plane", manager:findmap(mapname))
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightcolor(obj, 0.5, 0.5, 0.5, 1)
mapfunctions:setlightrange(obj, 6)
mapfunctions:setlightintensity(obj, 20)
manager:runscript("scripts/modules/rooms/ship1power.lua", mapname)
mapfunctions:destroyobj(cube)
mapfunctions:destroyobj(plane)
