mat1 = manager:loadmaterial("materials/standard metal pack/metal4/"..manager:getsetting("graphicstype")..".mat")
mat2 = manager:loadmaterial("materials/standard metal pack/metal2/"..manager:getsetting("graphicstype")..".mat")
plane = mapfunctions:createplane()
cube = mapfunctions:createcube()
mapfunctions:spawnobjects(-1, -1, 0, -1, 6, 3, 0, 270, 0, cube, 1, mapname, mat1)
mapfunctions:spawnobjects(-1, -1, 0, 5, -1, 3, 0, 180, 0, cube, 1, mapname, mat1)
mapfunctions:spawnobjects(5, -1, 0, 5, 6, 3, 0, 90, 0, cube, 1, mapname, mat1)
mapfunctions:spawnobjects(-1, 6, 0, 5, 6, 3, 0, 0, 0, cube, 1, mapname, mat1)
mapfunctions:spawnobjects(0, 0, 0, 5, 6, 0, 0, 0, 0, plane, 0, mapname, mat2)
mapfunctions:spawnobjects(0, 0, 3, 5, 6, 3, 180, 0, 0, plane, 1, mapname, mat2)
mapfunctions:spawnlocation(0, -1, 0, 0, -1, 3, mapname, mapname)
mapfunctions:spawnrunscript(0, -2, 0, 0, -2, 3, "scripts/map/exit.lua", mapname)
obj = mapfunctions:getobj(3, 3, 3, "plane", manager:findmap(mapname))
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightcolor(obj, 0.6, 0.3, 0.5, 1)
mapfunctions:setlightintensity(obj, 10)
mapfunctions:setlightrange(obj, 6)
mapfunctions:spawnlocation(0, 5, 0, 5, 5, 3, mapname, mapname)
mapfunctions:destroyobj(cube)
mapfunctions:destroyobj(plane)
