mat1 = manager:loadmaterial("materials/standard metal pack/metal/"..manager:getsetting("graphicstype")..".mat")
mat2 = manager:loadmaterial("materials/standard metal pack/metal2/"..manager:getsetting("graphicstype")..".mat")
mat3 = manager:loadmaterial("materials/standard metal pack/glass/"..manager:getsetting("graphicstype")..".mat")
plane = mapfunctions:createplane()
cube = mapfunctions:createcube()
mapfunctions:spawnobjects(-1, -1, 0, 10, -1, 3, 0, 180, 0, cube, 1, mapname, mat1)
mapfunctions:spawnobjects(10, -1, 0, 10, 10, 3, 0, 90, 0, cube, 1, mapname, mat1)
mapfunctions:spawnobjects(-1, -1, 0, -1, 10, 3, 0, 270, 0, cube, 1, mapname, mat1)
mapfunctions:changescale(cube, 0.1, 0.1, 0.1)
mapfunctions:spawnobjects(-1, 10, 1, 10, 10, 3, 0, 0, 0, cube, 1, mapname, mat3)
mapfunctions:changescale(cube, 1, 1, 1)
mapfunctions:spawnobjects(-1, 10, 0, 10, 0, 0, 0, 0, 0, cube, 1, mapname, mat3)
mapfunctions:spawnobjects(0, 0, 0, 10, 10, 0, 0, 0, 0, plane, 0, mapname, mat2)
mapfunctions:spawnobjects(0, 0, 3, 10, 10, 3, 180, 0, 0, plane, 1, mapname, mat1)
obj = mapfunctions:getobj(5, 5, 3, "plane", manager:findmap(mapname))
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightcolor(obj, 0.1, 1, 0.2, 1)
mapfunctions:setlightrange(obj, 10)
mapfunctions:setlightintensity(obj, 5)
mapfunctions:destroyobj(cube)
mapfunctions:destroyobj(plane)
mapfunctions:spawnlocation(0, 0, 0, 10, 0, 3, mapname, mapname)
