mat1 = manager:loadmaterial("materials/standard metal pack/steel/"..manager:getsetting("graphicstype")..".mat")
mat2 = manager:loadmaterial("materials/standard metal pack/metal3/"..manager:getsetting("graphicstype")..".mat")
plane = mapfunctions:createplane()
cube = mapfunctions:createcube()
mapfunctions:spawnobjects(0, 0, 0, 5, 10, 0, 0, 0, 0, plane, 0, mapname, mat2)
mapfunctions:spawnobjects(0, 0, 3, 5, 10, 3, 180, 0, 0, plane, 1, mapname, mat2)
mapfunctions:spawnobjects(-1, -1, 0, -1, 10, 3, 0, 270, 0, cube, 1, mapname, mat1)
mapfunctions:spawnobjects(5, -1, 0, 5, 10, 3, 0, 90, 0, cube, 1, mapname, mat1)
mapfunctions:spawnlocation(0, 0, 0, 5, 0, 3, mapname, mapname)
obj = mapfunctions:getobj(3, 5, 3, "plane", manager:findmap(mapname))
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightcolor(obj, 0.1, 0.5, 1, 1)
mapfunctions:setlightrange(obj, 10)
mapfunctions:setlightintensity(obj, 5)
mapfunctions:spawnlocation(0, 10, 0, 5, 10, 3, mapname, mapname)
mapfunctions:spawnlocation(5, 0, 0, 5, 9, 3, mapname, mapname)
mapfunctions:destroyobj(cube)
mapfunctions:destroyobj(plane)
