glaciermat = manager:loadmaterial("materials/standard planet pack/glacier/"..manager:getsetting("graphicstype")..".mat")
foundmap = manager:findmap(mapname)
startx = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "startx"))
starty = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "starty"))
startz = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "startz"))
endx = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "endx"))
endy = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "endy"))
endz = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "endz"))
orgtheta = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "orgtheta"))
cube = mapfunctions:createcube()
mapfunctions:spawnobjects(startx, starty, startz, endx, endy, endz, 0, orgtheta, 0, cube, 1, mapname, glaciermat)
mapfunctions:destroyobj(cube)
