foundmap = manager:findmap(mapname)
orgmap = manager:findmap(mapfunctions:checkstatetext(foundmap, "orgmap"))
objname = mapfunctions:checkstatetext(foundmap, "objname")
r = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "r"))
g = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "g"))
b = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "b"))
a = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "a"))
intensity = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "intensity"))
range = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "range"))
spawnx = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "spawnx"))
spawny = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "spawny"))
spawnz = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "spawnz"))
obj = mapfunctions:getobj(spawnx, spawny, spawnz, objname, orgmap)
mapfunctions:attachlight(obj, "point")
mapfunctions:setlightrange(obj, range)
mapfunctions:setlightintensity(obj, intensity)
mapfunctions:setlightcolor(obj, r, g, b, a)
mapfunctions:disablelight(obj)
manager:addfunction("scripts/modules/rooms/internal light/power.lua", "update", mapname)
