foundmap = manager:findmap(mapname)
buttonmat = manager:loadmaterial("materials/button/"..manager:getsetting("graphicstype")..".mat")
orgtheta = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "orgtheta"))
spawnx = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "spawnx"))
spawny = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "spawny"))
spawnz = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "spawnz"))
cube = mapfunctions:createcube()
mapfunctions:changescale(cube, 0.1, 0.1, 0.1)
gobj = mapfunctions:createobject()
obj = mapfunctions:spawnobject(spawnx +0.1, spawny, spawnz +0.3, 0, orgtheta, 0, cube, 1, mapname, buttonmat)
fus = mapfunctions:spawnobject(spawnx +0.1, spawny, spawnz +0.4, 0, orgtheta, 0, gobj, 1, mapname)
mapfunctions:attachtext(fus, "Fusion jump", 0.03)
mapfunctions:destroyobj(cube)
