foundmap = manager:findmap(mapname)
orgmap = mapfunctions:checkstatetext(foundmap, "orgmap")
mapscript = mapfunctions:checkstatetext(foundmap, "mapscript")
spawnx = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "spawnx"))
spawny = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "spawny"))
spawnz = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "spawnz"))
lengthx = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "lengthx"))
lengthy = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "lengthy"))
lengthz = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "lengthz"))
mapfunctions:spawnrunscript(spawnx, spawny, spawnz, spawnx +lengthx, spawny +lengthy, spawnz +lengthz, mapscript, orgmap)
