foundmap = manager:findmap(mapname)
orgmap = manager:findmap(mapfunctions:checkstatetext(foundmap, "orgmap"))
destroyx = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "destroyx"))
destroyy = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "destroyy"))
destroyz = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "destroyz"))
orgtheta = luafunctions:tofloatstr(mapfunctions:checkstatetext(foundmap, "orgtheta"))
mapfunctions:destroyobj(mapfunctions:getobj(destroyx, destroyy, destroyz, "cube", orgmap))
glassmat = manager:loadmaterial("materials/standard metal pack/glass/"..manager:getsetting("graphicstype")..".mat")
cube = mapfunctions:createcube()
obj = mapfunctions:spawnobject(0, 0, 0.9, 0, orgtheta, 0, cube, 1, mapname, glassmat)
mapfunctions:changescale(obj, 1, 0.1, 1)
obj = mapfunctions:spawnobject(0, 0, 0, 0, orgtheta, 0, cube, 1, mapname, glassmat)
mapfunctions:changescale(obj, 1, 0.1, 1)
obj = mapfunctions:spawnobject(-0.9, 0, 0, 0, orgtheta, 0, cube, 1, mapname, glassmat)
mapfunctions:changescale(obj, 0.1, 1, 0.1)
obj = mapfunctions:spawnobject(0.9, 0, 0, 0, orgtheta, 0, cube, 1, mapname, glassmat)
mapfunctions:changescale(obj, 0.1, 1, 0.1)
mapfunctions:destroyobj(cube)
